<a href="https://colab.research.google.com/github/vimalkumarasamy/Python/blob/master/Numpy_Experience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
squared_values = []
for number in range(10):
    squared_values.append(number*number)

print(squared_values)

# Square a list using NumPy
import numpy as np

vector = np.array(range(10))
scalar = 5
print(vector * scalar)
print(vector * vector)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  5 10 15 20 25 30 35 40 45]
[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
my_list = [1, 2, 3]
print(my_list)

import numpy as np

# converting a list to numpy array
my_vector = np.array(my_list)
print(my_vector)



[1, 2, 3]
[1 2 3]


In [11]:
# combining 2 lists as numpy array
my_matrix = np.array([my_list, my_list])
print(my_matrix)



[[1 2 3]
 [1 2 3]]


In [14]:
# stacking 2 lists one above the other vertical
x=np.vstack([my_list, my_list])
print(x)

[[1 2 3]
 [1 2 3]]


In [15]:
# stacking 2 lists horizontally
x=np.hstack([my_list, my_list])
print(x)

[1 2 3 1 2 3]


In [20]:
my_list1 = [[1,2], [3,4]]
my_list2 = [[5,6], [7,8]]  
np.hstack([my_list1, my_list2])   
# np.vstack([my_list1, my_list2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
my_list = range(10)
print(list(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
# creating a list directly
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# defining 2 dimensional arrays require additional brackets
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [53]:
np.ones(3)*3

array([3., 3., 3.])

In [60]:
# start, stop, how many values including the boundary conditions
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
# gives an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
x=np.empty(3)
print(x)

[1. 1. 1.]
