<a href="https://colab.research.google.com/github/vimalkumarasamy/Python/blob/master/Numpy_Experience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
squared_values = []
for number in range(10):
    squared_values.append(number*number)

print(squared_values)

# Square a list using NumPy
import numpy as np

vector = np.array(range(10))
scalar = 5
print(vector * scalar)
print(vector * vector)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  5 10 15 20 25 30 35 40 45]
[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
my_list = [1, 2, 3]
print(my_list)

import numpy as np

# converting a list to numpy array
my_vector = np.array(my_list)
print(my_vector)



[1, 2, 3]
[1 2 3]


In [11]:
# combining 2 lists as numpy array
my_matrix = np.array([my_list, my_list])
print(my_matrix)



[[1 2 3]
 [1 2 3]]


In [14]:
# stacking 2 lists one above the other vertical
x=np.vstack([my_list, my_list])
print(x)

[[1 2 3]
 [1 2 3]]


In [15]:
# stacking 2 lists horizontally
x=np.hstack([my_list, my_list])
print(x)

[1 2 3 1 2 3]


In [20]:
my_list1 = [[1,2], [3,4]]
my_list2 = [[5,6], [7,8]]  
np.hstack([my_list1, my_list2])   
# np.vstack([my_list1, my_list2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
my_list = range(10)
print(list(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
# creating a list directly
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# defining 2 dimensional arrays require additional brackets
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [53]:
np.ones(3)*3

array([3., 3., 3.])

In [60]:
# start, stop, how many values including the boundary conditions
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
# gives an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
x=np.empty(3)
print(x)

[1. 1. 1.]


In [72]:
np.random.randn(7)

array([-0.7144503 ,  0.80744412, -0.80836589, -0.43081643, -0.23374049,
       -0.79435867, -1.07139243])

In [75]:
np.random.randint(1,101,100)

array([16, 67, 39, 87, 32, 76, 14, 10, 48, 87, 87, 80, 18, 74,  7, 58, 24,
       82, 96, 76, 58, 90, 11, 20, 20, 10,  7, 63, 22, 94, 59, 53, 73, 42,
       72, 87, 54, 71, 44, 39, 82, 89,  9, 82, 86, 97,  2, 71, 12, 80, 84,
       76, 91, 55, 75, 11, 26, 32, 73, 59, 76, 59,  6, 27, 93, 70, 72, 32,
       55, 93, 45, 37, 89, 64, 47, 88, 53, 96, 66, 84, 96, 78, 51, 62, 11,
       23, 46, 74, 43, 48, 20, 39, 11, 11, 58, 91, 39, 11, 39, 52])

In [77]:
vector = np.arange(1,10)
print(vector.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
vector = np.random.randint(1,50,25)
# Min
print(vector)
# vector.min()
# Max
# vector.max()
# # get location of min value
index = vector.argmin()
print(index)
vector[index]
# # get location of max value
# index = vector.argmax()
# # get shape
# vector.shape

# my_matrix = vector.reshape(5, 5)
# my_matrix.shape

[16  6  2 47 49 35  7 19 31 37  3 34  1 15  7 26 14 25 44 26 22 11 43 35
 28]
12


1

In [98]:
vector=np.arange(10)
print(vector)
print(vector[3])
print(vector[2:4])
print(vector[2:])
# start:end:steps
print(vector[0:9:2])

[0 1 2 3 4 5 6 7 8 9]
3
[2 3]
[2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [99]:
print(vector)
vector[2:6]=100
print(vector)

[0 1 2 3 4 5 6 7 8 9]
[  0   1 100 100 100 100   6   7   8   9]
